module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
    screens: {
      xs: '414px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  variants: {
    extend: {
      margin: ['active'],
      padding: ['active'],
      width: ['active'],
      height: ['active'],
      boxShadow: ['active'],
      translate: ['active'],
      scale: ['active'],
      display: [
        'children',
        'DEFAULT',
        'children-first',
        'children-last',
        'children-odd',
        'children-even',
        'children-not-first',
        'children-not-last',
        'children-hover',
        'hover',
        'children-focus',
        'focus',
        'children-focus-within',
        'focus-within',
        'children-active',
        'active',
        'children-visited',
        'visited',
        'children-disabled',
        'disabled',
        'responsive',
      ],
    },
  },
  plugins: [require('tailwindcss-textshadow'), require('tailwindcss-children')],
};
